name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image for linting/formatting
        run: docker build -t linting-formatting .

      - name: Run linting with Docker
        run: docker run --rm linting-formatting npm run lint

      - name: Run formatting check with Docker
        run: docker run --rm linting-formatting npm run format -- --check
