name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image for linting/formatting
        run: docker build -t linting-formatting .

      - name: Run linting with Docker
        run: docker run --rm linting-formatting npm run lint

      - name: Run formatting check with Docker
        run: docker run --rm linting-formatting npm run format -- --check

      - name: Set up Node.js for testing
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies for testing
        run: npm install

      - name: Test with Jest
        run: npm test

      - name: Audit dependencies
        run: npm audit --audit-level=high

